desc: Take Screen shots
keybinding: Ctrl+A
name: Screen shot
supported_os:
  linux:
    gnome:
      cmd: kitty -e "echo taking screenshot"
      dependency: scrot-gnome
      script_path: scrot-gnome
    hyprland:
      cmd: kitty -e "echo taking screenshot"
      dependency: scrot
      script_path: ''

  win32:
    windows10:
      cmd: notepad 
      dependency: notepad
      script_path: notepad      

