desc: Take Screen shots
keybinding: Ctrl+I
name: Screen shot
supported_os:
  linux:
    gnome:
      cmd: scrot-gnome
      dependency: scrot-gnome
      script_path: scrot-gnome
    hyprland:
      cmd: scrot -e
      dependency: scrot
      script_path: ''
