desc: Take Screen shots
keybinding: Ctrl+Shift+S
name: Screen shot
supported_os:
  linux:
    gnome:
      cmd: scrot-gnome
      dependency: scrot-gnome
      script_path: ''
    hyprland:
      cmd: scrot
      dependency: scrot
      script_path: ''

  win32:
    windows10:
      cmd: notepad 
      dependency: notepad
      script_path: notepad      

