name: "screen recording"
desc: "Take Screen recording"
keybinding: Ctrl+Shift+j
supported_os:
  linux:
    hyprland:
      cmd: "ffmpeg"
      dependency: "ffmpeg"
      script_path: ""

    gnome:
      cmd: "ffmpeg"
      dependency: "ffmpeg"
      script_path: ""
