desc: Take Screen shots
keybinding: Ctrl+I
name: Screen shot
supported_os:
  linux:
    gnome:
      cmd: kitty -e "echo taking screenshot"
      dependency: scrot-gnome
      script_path: scrot-gnome
    hyprland:
      cmd: kitty -e "echo taking screenshot"
      dependency: scrot
      script_path: ''
