desc: Take screen recording
keybinding: Ctrl+S
name: screen recording
supported_os:
  linux:
    gnome:
      cmd: ffmpeg
      dependency: ffmpeg
      script_path: ''
    hyprland:
      cmd: echo screen recording
      dependency: ffmpeg
      script_path: ffmpeg
  windows:
    windows10:
      cmd: powershell screenroctd
      dependency: powershell
      script_path: ''
