screenshot:
  name: "Screen shot"
  desc: "Take Screen shots"
  keybinding: super-shift-s
  supported_os:
    linux:
      hyprland:
        cmd: "scrot"
        dependency: "scrot"
        script_path: ""

      gnome:
        cmd: "scrot-gnome"
        dependency: "scrot-gnome"
        script_path: ""
